; Тестовый файл для автозапуска
; Строка коментариев, всегда игнорируется
; Имя файла для запуска без путей, файл должен лежать в корне SD карты
; Имя файла должно начинаться с начала строки с подстроки "File=" можно в любом регистре, как удобнее
; На данный момент умеет только Hobeta файлы (расширение только "$C")
File=rage.$C
