$(TARGET): $(OBJECTS) $(FPGACORE)

        $(CC) $(LDFLAGS) $(OBJECTS) $(FPGACORE) $(LIBDIRS) $(LIBS) -o $(TARGET)



top.rbf: ../../../fpga/current/quartus/top.rbf

       cp ../../../fpga/current/quartus/top.rbf top.rbf



$(FPGACORE): top.rbf

       ../../../tools/mhmt/mhmt -maxwin2048 top.rbf top.mlz

       avr-objcopy -I binary -O elf32-avr --rename-section .data=.progmem.data,contents,alloc,load,readonly,data --redefine-sym _binary_top_mlz_start=fpga --redefine-sym _binary_top_mlz_end=fpga_end top.mlz top.o



%.hex: $(TARGET)

       avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@



%.eep: $(TARGET)

       avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0



%.lss: $(TARGET)

       avr-objdump -h -S $< > $@



size: ${TARGET}

       @echo

       @avr-size -C --mcu=${MCU} ${TARGET}



zxevo_fw.bin: core.hex core.eep

       ../../../tools/make_fw/make_fw core.hex core.eep version.txt