ECHO CLEAN
PAUSE

del /Q /F		emul.o
del /Q /F		std.o
del /Q /F		atm.o
del /Q /F		cheat.o
del /Q /F		config.o
del /Q /F		dbgbpx.o
del /Q /F		dbgcmd.o
del /Q /F		dbglabls.o
del /Q /F		dbgmem.o
del /Q /F		dbgoth.o
del /Q /F		dbgpaint.o
del /Q /F		dbgreg.o
del /Q /F		dbgrwdlg.o
del /Q /F		dbgtrace.o
del /Q /F		debug.o
del /Q /F		draw.o
del /Q /F		drawnomc.o
del /Q /F		draw_384.o
del /Q /F		dx.o
del /Q /F		dxerr.o
del /Q /F		dxovr.o
del /Q /F		dxrcopy.o
del /Q /F		dxrend.o
del /Q /F		dxrendch.o
del /Q /F		dxrframe.o
del /Q /F		dxr_4bpp.o
del /Q /F		dxr_512.o
del /Q /F		dxr_advm.o
del /Q /F		dxr_atm.o
del /Q /F		dxr_atm0.o
del /Q /F		dxr_atm2.o
del /Q /F		dxr_atm4.o
del /Q /F		dxr_atm6.o
del /Q /F		dxr_atm7.o
del /Q /F		profi.o
del /Q /F		dxr_atmf.o
del /Q /F		dxr_prof.o
del /Q /F		dxr_rsm.o
del /Q /F		dxr_text.o
del /Q /F		dxr_vd.o
del /Q /F		emulkeys.o
del /Q /F		fntsrch.o
del /Q /F		font.o
del /Q /F		font14.o
del /Q /F		font16.o
del /Q /F		font8.o
del /Q /F		fontatm2.o
del /Q /F		fontdata.o
del /Q /F		gs.o
del /Q /F		gshlbass.o
del /Q /F		gshle.o
del /Q /F		gsz80.o
del /Q /F		gui.o
del /Q /F		hdd.o
del /Q /F		hddio.o
del /Q /F		iehelp.o
del /Q /F		init.o
del /Q /F		input.o
del /Q /F		inputpc.o
del /Q /F		io.o
del /Q /F		keydefs.o
del /Q /F		leds.o
del /Q /F		mainloop.o
del /Q /F		memory.o
del /Q /F		modem.o
del /Q /F		opendlg.o
del /Q /F		savesnd.o
del /Q /F		sdcard.o
del /Q /F		snapshot.o
del /Q /F		snd_bass.o
del /Q /F		sound.o
del /Q /F		sshot_png.o
del /Q /F		tape.o
del /Q /F		util.o
del /Q /F		vars.o
del /Q /F		vs1001.o
del /Q /F		wd93cmd.o
del /Q /F		wd93crc.o
del /Q /F		fdd.o
del /Q /F		upd765.o
del /Q /F		wd93trk.o
del /Q /F		wldr_fdi.o
del /Q /F		wldr_isd.o
del /Q /F		wldr_pro.o
del /Q /F		wldr_td0.o
del /Q /F		wldr_trd.o
del /Q /F		wldr_udi.o
del /Q /F		wldr_dsk.o
del /Q /F		wldr_ipf.o
del /Q /F		z80.o
del /Q /F		z80asm.o
del /Q /F		zc.o
del /Q /F		savevid.o

del /Q /F		zxusbnet.o
del /Q /F		zxevo.o
del /Q /F		dxr_pentatm7.o

del /Q /F		debug_tools.o
del /Q /F		midi.o

del /Q /F		settings.o

